plugins {
    id 'com.android.application'
}

android {
    namespace 'vn.example.ch34aidlclient'
    compileSdk 34

    defaultConfig {
        applicationId "vn.example.ch34aidlclient"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildFeatures {
        viewBinding true
        aidl true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // KHÔNG có implementation project(':server') — hai app này ĐỘC LẬP hoàn
    // toàn, chỉ dùng chung định nghĩa file .aidl (chép tay, xem mục 34.2).
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
